name: happy_tech_mastering_api_with_flutter
description: "A new Flutter project."
# Prevents accidental publishing to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number for your application
version: 1.0.0+1
environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Flutter packages
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  image_picker: ^1.0.7
  dio: ^5.4.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for good coding practices
  flutter_lints: ^4.0.0

flutter:
  # Use material design
  uses-material-design: true

  # Asset declaration
  assets:
    - assets/images/

  # Custom fonts declaration
  fonts:
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-Regular.ttf
        - asset: assets/fonts/NotoSerif-Bold.ttf
          weight: 700
